service: hello-api
runtime: nodejs
entry: src/index.ts

providers:
  - cloudflare-workers

state:
  backend: local
  local:
    dir: ./.runfabric/state

triggers:
  - type: http
    method: GET
    path: /hello
