service: hello-worker
runtime: nodejs
entry: src/index.ts

providers:
  - gcp-functions

state:
  backend: local
  local:
    dir: ./.runfabric/state

triggers:
  - type: http
    method: POST
    path: /work
