service: hello-api
runtime: nodejs
entry: src/index.ts

providers:
  - aws-lambda

state:
  backend: gcs
  gcs:
    bucket: ${env:RUNFABRIC_STATE_GCS_BUCKET}
    prefix: runfabric/state

triggers:
  - type: http
    method: GET
    path: /hello
